name: sefm
channels:
 - conda-forge
 - pyviz
dependencies:
 - python=3.7*
 - pip=20
 - cartopy
 - dask-ml
 - datashader
 - descartes
 - firefox
 - flask
 - flask-sqlalchemy
 - fsspec
 - gcsfs
 - geckodriver
 - geopandas
 - geoviews-core
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-geopandas
 - intake-xarray
 - ipywidgets
 - ipyleaflet
 - jupyter-panel-proxy
 - jupyter_contrib_nbextensions
 - jupyter_nbextensions_configurator
 - lz4
 - matplotlib-base
 - nbsite
 - nomkl
 - numpy
 - numcodecs
 - pandas
 - panel
 - plotly
 - prefect
 - pyarrow
 - pydap
 - python-blosc
 - python-dotenv
 - rasterio
 - rio-cogeo
 - retrying
 - s3fs
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - selenium
 - sphinx_holoviz_theme
 - rpy2
 - xarray
 - zarr
 - pip:
    - git+https://github.com/hydrologie/sefm.git