name: env
channels:
 - conda-forge
dependencies:
 - python=3.7*
 - pip=20
 - cartopy
 - dask-ml
 - datashader
 - descartes
 - flask
 - flask-sqlalchemy
 - fsspec
 - gcsfs
 - geopandas
 - geoviews-core
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipywidgets
 - ipyleaflet
 - jupyter-panel-proxy
 - lz4
 - matplotlib-base
 - metpy
 - nomkl
 - numpy
 - numcodecs
 - pandas
 - panel
 - plotly
 - prefect
 - pydap
 - python-blosc
 - python-dotenv
 - rasterio
 - rio-cogeo
 - retrying
 - s3fs
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - sparse
 - tiledb-py
 - xarray
 - xesmf
 - xpublish
 - zarr